In [1]:
import os
import numpy as np
import pandas as pd
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import matplotlib.pyplot as plt
import seaborn as sns
import copy

In [2]:
import gc
gc.enable()

In [3]:
#PATH = '../finanz_vs_news'
PATH = r'..\HackathonDaten\Nachrichten und Kurse\\'

### Read in company ticker names

In [4]:
companies = pd.read_pickle('TickerDic.pickle')

In [5]:
companies.head()

,Ticker,Name,Category Name,RedName
0,AFL,Aflac Incorporated,Accident & Health Insurance,Aflac
1,AIZ,"Assurant, Inc.",Accident & Health Insurance,Assurant
23,UNM,Unum Group,Accident & Health Insurance,Unum
52,IPG,"The Interpublic Group of Companies, Inc.",Advertising Agencies,Interpublic
57,OMC,Omnicom Group Inc.,Advertising Agencies,Omnicom

In [9]:
company_names = companies['RedName'].tolist()

In [6]:
companies.query('RedName == "BlackRock"')

    Ticker             Name     Category Name    RedName
966    BLK  BlackRock, Inc.  Asset Management  BlackRock

### Red in neg/pos dictionaries

In [7]:
pos_words = pd.read_pickle('DicPositiveWords.pickle')
neg_words = pd.read_pickle('DicNegativeWords.pickle')

### Do bag of words

In [8]:
import helpers

In [ ]:
%%time
reu_file_list = [f for f in os.listdir(PATH+'Reuters_US/') if '_2007' in f]
media_attention = []

for date_file in reu_file_list[:]:
    #print(date_file)
    df_tmp = pd.read_csv(PATH+'Reuters_US/'+date_file,
                         delimiter=';', 
                         parse_dates=[0], 
                         names=['Time', 'Short_Msg', 'Long_Msg', 'Link']
                        ).iloc[:,[0,2]].dropna()
    df_tmp = df_tmp.set_index('Time')
    if df_tmp.shape[0] ==0:
        continue
    df_tmp2 = helpers.count_sensitive_words(df_tmp.copy(deep=True), 
                                        ["Morgan Stanley", "Goldman Sachs", "BlackRock"]+[{'positive': pos_words[:70].values.tolist()},
                                                       {'negative': neg_words[:70].values.tolist()}
                                                      ], 
                                        companies_neg_pos=["Morgan Stanley", "Goldman Sachs", "BlackRock"], str_col='Long_Msg')
        
    media_attention.append(df_tmp2)
    #break

reuters_us_news_20070101.csv
reuters_us_news_20070102.csv
reuters_us_news_20070103.csv
reuters_us_news_20070104.csv
reuters_us_news_20070105.csv
reuters_us_news_20070106.csv
reuters_us_news_20070107.csv
reuters_us_news_20070108.csv
reuters_us_news_20070109.csv
reuters_us_news_20070110.csv
reuters_us_news_20070111.csv
reuters_us_news_20070112.csv
reuters_us_news_20070113.csv
reuters_us_news_20070114.csv
reuters_us_news_20070115.csv
reuters_us_news_20070116.csv
reuters_us_news_20070117.csv
reuters_us_news_20070118.csv
reuters_us_news_20070119.csv
reuters_us_news_20070120.csv
reuters_us_news_20070121.csv
reuters_us_news_20070122.csv
reuters_us_news_20070123.csv
reuters_us_news_20070124.csv
reuters_us_news_20070125.csv
reuters_us_news_20070126.csv
reuters_us_news_20070127.csv
reuters_us_news_20070128.csv
reuters_us_news_20070129.csv
reuters_us_news_20070130.csv
reuters_us_news_20070131.csv
reuters_us_news_20070201.csv
reuters_us_news_20070202.csv
reuters_us_news_20070203.csv
reuters_us_news_20070204.csv
reuters_us_news_20070205.csv
reuters_us_news_20070206.csv
reuters_us_news_20070207.csv
reuters_us_news_20070208.csv
reuters_us_news_20070209.csv
reuters_us_news_20070210.csv
reuters_us_news_20070211.csv
reuters_us_news_20070212.csv
reuters_us_news_20070213.csv
reuters_us_news_20070214.csv
reuters_us_news_20070215.csv
reuters_us_news_20070216.csv
reuters_us_news_20070217.csv
reuters_us_news_20070218.csv
reuters_us_news_20070219.csv
reuters_us_news_20070220.csv
reuters_us_news_20070221.csv
reuters_us_news_20070222.csv
reuters_us_news_20070223.csv
reuters_us_news_20070224.csv
reuters_us_news_20070225.csv
reuters_us_news_20070226.csv
reuters_us_news_20070227.csv
reuters_us_news_20070228.csv
reuters_us_news_20070301.csv
reuters_us_news_20070302.csv
reuters_us_news_20070303.csv
reuters_us_news_20070304.csv
reuters_us_news_20070305.csv
reuters_us_news_20070306.csv
reuters_us_news_20070307.csv
reuters_us_news_20070308.csv
reuters_us_news_20070309.csv
reuters_us_news_20070310.csv
reuters_us_news_20070311.csv
reuters_us_news_20070312.csv
reuters_us_news_20070313.csv
reuters_us_news_20070314.csv
reuters_us_news_20070315.csv
reuters_us_news_20070316.csv
reuters_us_news_20070317.csv
reuters_us_news_20070318.csv
reuters_us_news_20070319.csv
reuters_us_news_20070320.csv
reuters_us_news_20070321.csv
reuters_us_news_20070322.csv
reuters_us_news_20070323.csv
reuters_us_news_20070324.csv
reuters_us_news_20070325.csv
reuters_us_news_20070326.csv
reuters_us_news_20070327.csv
reuters_us_news_20070328.csv
reuters_us_news_20070329.csv
reuters_us_news_20070330.csv
reuters_us_news_20070331.csv
reuters_us_news_20070401.csv
reuters_us_news_20070402.csv
reuters_us_news_20070403.csv
reuters_us_news_20070404.csv
reuters_us_news_20070405.csv
reuters_us_news_20070406.csv
reuters_us_news_20070407.csv
reuters_us_news_20070408.csv
reuters_us_news_20070409.csv
reuters_us_news_20070410.csv
reuters_us_news_20070411.csv
reuters_us_news_20070412.csv
reuters_us_news_20070413.csv
reuters_us_news_20070414.csv
reuters_us_news_20070415.csv
reuters_us_news_20070416.csv
reuters_us_news_20070417.csv
reuters_us_news_20070418.csv
reuters_us_news_20070419.csv
reuters_us_news_20070420.csv
reuters_us_news_20070421.csv
reuters_us_news_20070422.csv
reuters_us_news_20070423.csv
reuters_us_news_20070424.csv
reuters_us_news_20070425.csv
reuters_us_news_20070426.csv
reuters_us_news_20070427.csv
reuters_us_news_20070428.csv
reuters_us_news_20070429.csv
reuters_us_news_20070430.csv
reuters_us_news_20070501.csv
reuters_us_news_20070502.csv
reuters_us_news_20070503.csv
reuters_us_news_20070504.csv
reuters_us_news_20070505.csv
reuters_us_news_20070506.csv
reuters_us_news_20070507.csv
reuters_us_news_20070508.csv
reuters_us_news_20070509.csv
reuters_us_news_20070510.csv
reuters_us_news_20070511.csv
reuters_us_news_20070512.csv
reuters_us_news_20070513.csv
reuters_us_news_20070514.csv
reuters_us_news_20070515.csv
reuters_us_news_20070516.csv
reuters_us_news_20070517.csv
reuters_us_news_20070518.csv
reuters_us_news_20070519.csv
reuters_us_news_20070520.csv
reuters_us_news_20070521.csv
reuters_us_news_20070522.csv
reuters_us_news_20070523.csv
reuters_us_news_20070524.csv
reuters_us_news_20070525.csv
reuters_us_news_20070526.csv
reuters_us_news_20070527.csv
reuters_us_news_20070528.csv
reuters_us_news_20070529.csv
reuters_us_news_20070530.csv
reuters_us_news_20070531.csv
reuters_us_news_20070601.csv
reuters_us_news_20070602.csv
reuters_us_news_20070603.csv
reuters_us_news_20070604.csv
reuters_us_news_20070605.csv
reuters_us_news_20070606.csv
reuters_us_news_20070607.csv
reuters_us_news_20070608.csv
reuters_us_news_20070609.csv
reuters_us_news_20070610.csv
reuters_us_news_20070611.csv
reuters_us_news_20070612.csv
reuters_us_news_20070613.csv
reuters_us_news_20070614.csv
reuters_us_news_20070615.csv
reuters_us_news_20070616.csv
reuters_us_news_20070617.csv
reuters_us_news_20070618.csv
reuters_us_news_20070619.csv
reuters_us_news_20070620.csv
reuters_us_news_20070621.csv
reuters_us_news_20070622.csv
reuters_us_news_20070623.csv
reuters_us_news_20070624.csv
reuters_us_news_20070625.csv
reuters_us_news_20070626.csv
reuters_us_news_20070627.csv
reuters_us_news_20070628.csv
reuters_us_news_20070629.csv
reuters_us_news_20070630.csv
reuters_us_news_20070701.csv
reuters_us_news_20070702.csv
reuters_us_news_20070703.csv
reuters_us_news_20070704.csv
reuters_us_news_20070705.csv
reuters_us_news_20070706.csv
reuters_us_news_20070707.csv
reuters_us_news_20070708.csv
reuters_us_news_20070709.csv
reuters_us_news_20070710.csv
reuters_us_news_20070711.csv
reuters_us_news_20070712.csv
reuters_us_news_20070713.csv
reuters_us_news_20070714.csv
reuters_us_news_20070715.csv
reuters_us_news_20070716.csv
reuters_us_news_20070717.csv
reuters_us_news_20070718.csv
reuters_us_news_20070719.csv
reuters_us_news_20070720.csv
reuters_us_news_20070721.csv
reuters_us_news_20070722.csv
reuters_us_news_20070723.csv
reuters_us_news_20070724.csv
reuters_us_news_20070725.csv
reuters_us_news_20070726.csv
reuters_us_news_20070727.csv
reuters_us_news_20070728.csv
reuters_us_news_20070729.csv
reuters_us_news_20070730.csv
reuters_us_news_20070731.csv
reuters_us_news_20070801.csv
reuters_us_news_20070802.csv
reuters_us_news_20070803.csv
reuters_us_news_20070804.csv
reuters_us_news_20070805.csv
reuters_us_news_20070806.csv
reuters_us_news_20070807.csv
reuters_us_news_20070808.csv
reuters_us_news_20070809.csv
reuters_us_news_20070810.csv
reuters_us_news_20070811.csv
reuters_us_news_20070812.csv
reuters_us_news_20070813.csv
reuters_us_news_20070814.csv
reuters_us_news_20070815.csv
reuters_us_news_20070816.csv
reuters_us_news_20070817.csv
reuters_us_news_20070818.csv
reuters_us_news_20070819.csv
reuters_us_news_20070820.csv
reuters_us_news_20070821.csv
reuters_us_news_20070822.csv
reuters_us_news_20070823.csv
reuters_us_news_20070824.csv
reuters_us_news_20070825.csv
reuters_us_news_20070826.csv
reuters_us_news_20070827.csv
reuters_us_news_20070828.csv
reuters_us_news_20070829.csv
reuters_us_news_20070830.csv
reuters_us_news_20070831.csv
reuters_us_news_20070901.csv
reuters_us_news_20070902.csv
reuters_us_news_20070903.csv
reuters_us_news_20070904.csv
reuters_us_news_20070905.csv
reuters_us_news_20070906.csv
reuters_us_news_20070907.csv
reuters_us_news_20070908.csv
reuters_us_news_20070909.csv
reuters_us_news_20070910.csv
reuters_us_news_20070911.csv
reuters_us_news_20070912.csv
reuters_us_news_20070913.csv
reuters_us_news_20070914.csv
reuters_us_news_20070915.csv
reuters_us_news_20070916.csv
reuters_us_news_20070917.csv
reuters_us_news_20070918.csv
reuters_us_news_20070919.csv
reuters_us_news_20070920.csv
reuters_us_news_20070921.csv
reuters_us_news_20070922.csv
reuters_us_news_20070923.csv
reuters_us_news_20070924.csv
reuters_us_news_20070925.csv
reuters_us_news_20070926.csv
reuters_us_news_20070927.csv
reuters_us_news_20070928.csv
reuters_us_news_20070929.csv
reuters_us_news_20070930.csv
reuters_us_news_20071001.csv
reuters_us_news_20071002.csv
reuters_us_news_20071003.csv
reuters_us_news_20071004.csv
reuters_us_news_20071005.csv
reuters_us_news_20071006.csv
reuters_us_news_20071007.csv
reuters_us_news_20071008.csv
reuters_us_news_20071009.csv
reuters_us_news_20071010.csv

reuters_us_news_20071011.csv
reuters_us_news_20071012.csv
reuters_us_news_20071013.csv
reuters_us_news_20071014.csv
reuters_us_news_20071015.csv
reuters_us_news_20071016.csv
reuters_us_news_20071017.csv
reuters_us_news_20071018.csv
reuters_us_news_20071019.csv
reuters_us_news_20071020.csv
reuters_us_news_20071021.csv
reuters_us_news_20071022.csv
reuters_us_news_20071023.csv
reuters_us_news_20071024.csv
reuters_us_news_20071025.csv
reuters_us_news_20071026.csv
reuters_us_news_20071027.csv
reuters_us_news_20071028.csv
reuters_us_news_20071029.csv
reuters_us_news_20071030.csv
reuters_us_news_20071031.csv
reuters_us_news_20071101.csv
reuters_us_news_20071102.csv
reuters_us_news_20071103.csv
reuters_us_news_20071104.csv
reuters_us_news_20071105.csv
reuters_us_news_20071106.csv
reuters_us_news_20071107.csv
reuters_us_news_20071108.csv
reuters_us_news_20071109.csv
reuters_us_news_20071110.csv
reuters_us_news_20071111.csv
reuters_us_news_20071112.csv
reuters_us_news_20071113.csv
reuters_us_news_20071114.csv
reuters_us_news_20071115.csv
reuters_us_news_20071116.csv
reuters_us_news_20071117.csv
reuters_us_news_20071118.csv
reuters_us_news_20071119.csv
reuters_us_news_20071120.csv
reuters_us_news_20071121.csv
reuters_us_news_20071122.csv
reuters_us_news_20071123.csv
reuters_us_news_20071124.csv
reuters_us_news_20071125.csv
reuters_us_news_20071126.csv
reuters_us_news_20071127.csv
reuters_us_news_20071128.csv

In [10]:
media_attention2 = copy.deepcopy(media_attention)
media_attention2 = pd.concat(media_attention2).sort_values(by=['Time'])
# output dataset grouped by day
media_attention2 = media_attention2.resample('1D').sum()

In [11]:
media_attention2

,Morgan_Stanley_count,Goldman_Sachs_count,BlackRock_count,positive_count,negative_count,Morgan_Stanley_positive_count,Morgan_Stanley_negative_count,Goldman_Sachs_positive_count,Goldman_Sachs_negative_count,BlackRock_positive_count,BlackRock_negative_count,total_msg_count
Time,,,,,,,,,,,,
2007-01-12,0,0,0,1,3,0,0,0,0,0,0,1
2007-01-13,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-14,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-15,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-16,0,0,0,3,7,0,0,0,0,0,0,1
2007-01-17,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-18,0,0,0,0,6,0,0,0,0,0,0,1
2007-01-19,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-20,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-21,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-22,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-23,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-24,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-25,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-26,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-27,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-28,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-29,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-30,0,0,0,0,0,0,0,0,0,0,0,0
2007-01-31,0,0,0,4,1,0,0,0,0,0,0,3
2007-02-01,0,0,0,0,5,0,0,0,0,0,0,1
2007-02-02,0,0,0,0,0,0,0,0,0,0,0,0
2007-02-03,0,0,0,0,0,0,0,0,0,0,0,0
2007-02-04,0,0,0,0,0,0,0,0,0,0,0,0
2007-02-05,0,0,0,0,0,0,0,0,0,0,0,0
2007-02-06,0,0,0,0,0,0,0,0,0,0,0,0
2007-02-07,0,0,0,0,0,0,0,0,0,0,0,0
2007-02-08,0,0,0,0,0,0,0,0,0,0,0,0
2007-02-09,0,0,0,0,0,0,0,0,0,0,0,0
2007-02-10,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
2014-04-10,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-11,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-12,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-13,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-14,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-15,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-16,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-17,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-18,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-19,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-20,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-21,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-22,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-23,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-24,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-25,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-26,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-27,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-28,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-29,0,0,0,0,0,0,0,0,0,0,0,0
2014-04-30,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-01,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-02,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-03,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-04,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-05,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-06,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-07,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-08,0,0,0,0,0,0,0,0,0,0,0,0
2014-05-09,0,0,0,0,0,0,0,0,0,0,0,1

In [12]:
media_attention2 = helpers.fe(media_attention2)

In [13]:
media_attention2.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2675 entries, 2007-01-12 to 2014-05-09
Freq: D
Data columns (total 23 columns):
Morgan_Stanley_count             2675 non-null int64
Goldman_Sachs_count              2675 non-null int64
BlackRock_count                  2675 non-null int64
positive_count                   2675 non-null int64
negative_count                   2675 non-null int64
Morgan_Stanley_positive_count    2675 non-null int64
Morgan_Stanley_negative_count    2675 non-null int64
Goldman_Sachs_positive_count     2675 non-null int64
Goldman_Sachs_negative_count     2675 non-null int64
BlackRock_positive_count         2675 non-null int64
BlackRock_negative_count         2675 non-null int64
total_msg_count                  2675 non-null int64
Morgan_Stanley_frac              423 non-null float64
Goldman_Sachs_frac               423 non-null float64
BlackRock_frac                   423 non-null float64
positive_frac                    423 non-null float64
negative_frac                    423 non-null float64
Morgan_Stanley_positive_frac     423 non-null float64
Morgan_Stanley_negative_frac     423 non-null float64
Goldman_Sachs_positive_frac      423 non-null float64
Goldman_Sachs_negative_frac      423 non-null float64
BlackRock_positive_frac          423 non-null float64
BlackRock_negative_frac          423 non-null float64
dtypes: float64(11), int64(12)
memory usage: 501.6 KB

In [14]:
media_attention2.sum().sort_values(ascending=False)

positive_count                   4.336142e+06
negative_count                   2.695209e+06
total_msg_count                  7.621350e+05
Goldman_Sachs_positive_count     1.437970e+05
Morgan_Stanley_negative_count    1.334270e+05
Goldman_Sachs_negative_count     1.273140e+05
Morgan_Stanley_positive_count    1.214260e+05
BlackRock_positive_count         9.541500e+04
BlackRock_negative_count         8.161300e+04
Morgan_Stanley_count             2.259000e+04
Goldman_Sachs_count              1.593600e+04
BlackRock_count                  6.895000e+03
positive_frac                    1.896724e+03
negative_frac                    1.351577e+03
Morgan_Stanley_negative_frac     6.181094e+01
Morgan_Stanley_positive_frac     5.680776e+01
Goldman_Sachs_positive_frac      5.137416e+01
Goldman_Sachs_negative_frac      4.945442e+01
BlackRock_positive_frac          4.895128e+01
BlackRock_negative_frac          3.119134e+01
Morgan_Stanley_frac              9.652851e+00
Goldman_Sachs_frac               7.260564e+00
BlackRock_frac                   4.233885e+00
dtype: float64

In [15]:
print('Numbers of negative and positive mentions of Morgan Stanley are: {} and {}'.format(media_attention2['Morgan_Stanley_negative_count'].sum(),
                                                                                   media_attention2['Morgan_Stanley_positive_count'].sum())
     )

Numbers of negative and positive mentions of Morgan Stanley are: 133427 and 121426

#### Save the pre-processed media dataset

In [16]:
media_attention2.to_csv('MediaAttentionLong_2007.csv')
#media_attention2.to_csv('MediaAttentionLong_2008.csv')